sudo: required
language: node_js
node_js:
  - "0.10"
before_install:
  - curl https://install.meteor.com | /bin/sh
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email: false
script:
  - JASMINE_BROWSER=PhantomJS meteor --test
